---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-example-octodex
  labels:
    app: aws-example-octodex
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: aws-example-octodex
  template:
    metadata:
      labels:
        app: aws-example-octodex
    spec:
      containers:
      - name: aws-example-octodex
        # image: 00000000000000.dkr.ecr.my-region.amazonaws.com/example-eks:tag
        image: 618668373247.dkr.ecr.eu-central-1.amazonaws.com/example-eks:2978ea966df2268acd7fac10abf3ec7fb13c49c9
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
